xdecor = {}
local modpath = minetest.get_modpath("xdecor")

dofile(modpath.."/handlers/animations.lua")
dofile(modpath.."/handlers/nodeboxes.lua")
dofile(modpath.."/handlers/registration.lua")
dofile(modpath.."/craftitems.lua")
dofile(modpath.."/legacy.lua")
dofile(modpath.."/recipes.lua")
dofile(modpath.."/enchanting.lua")
dofile(modpath.."/hive.lua")
dofile(modpath.."/itemframe.lua")
dofile(modpath.."/mailbox.lua")
dofile(modpath.."/rope.lua")
dofile(modpath.."/nodes.lua")
dofile(modpath.."/cooking.lua")
dofile(modpath.."/worktable.lua")
--dofile(modpah.."/xwall.lua")
dofile(modpath.."/craftguide.lua")
dofile(modpath.."/craftbook.lua")
